<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Role extends \Spatie\Permission\Models\Role
{
    use HasFactory;

    protected $table = 'roles';
    public $timestamps = false;

    public function users(): BelongsToMany
    {
        return parent::users()->select('id', 'first_name', 'last_name', 'email');
    }

    public function permissions(): BelongsToMany
    {
        return parent::permissions(); // TODO: Change the autogenerated stub
    }
}
